version: "3.9"

services:
  # Node.js App
  chatbot:
    container_name: chatbot
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app
    depends_on:
      - ollama
    environment:
      - PORT=3000
      - ORIGIN=https://thor.indietools.dev

  # Ollama Service
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

networks:
  default:
    name: cloudflare
    external: true

volumes:
  ollama:
